<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="a" nsURI="http://A/1.0" nsPrefix="a">
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refa" eType="plateforme://test#//B" />
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="B">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType plateforme://eclipse.stuff/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="C">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toa" eType="ecore:EClass plateforme://sibling/A.ecore#//A"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tobug" eType="ecore:EClass plateforme://sib/A.ecore#//A"/>
  </eClassifiers>
</ecore:EPackage>
