<?xml version='1.0' encoding='UTF-8'?>
<ecore:EPackage xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmi:version="2.0" nsURI="dpack" nsPrefix="sspack" name="pack">
  <eClassifiers xsi:type="ecore:EClass" name="A">
    <eStructuralFeatures xsi:type="ecore:EReference" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" name="element"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" name="name"/>
  </eClassifiers>
</ecore:EPackage>
