<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mytest" nsURI="mytest" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="A">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="b" eType="#//B" eOpposite="#//B/a"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="B">
    <eStructuralFeatures xsi:type="ecore:EReference" name="a" eType="#//A" eOpposite="#//A/b"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MyRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aContainer" upperBound="-1"
        eType="#//A" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bContainer" upperBound="-1"
        eType="#//B" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
